plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.myapplication'
    compileSdk 34

    defaultConfig {
        applicationId 'com.example.myapplication'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.10.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // Google Maps
    implementation 'com.google.android.gms:play-services-maps:18.2.0'
    implementation 'com.google.android.gms:play-services-location:21.0.1'
}

def backupDir = file("${rootProject.projectDir}/../downloads/Android/backup")

task copyReleaseApk(type: Copy, dependsOn: 'assembleRelease') {
    from "${buildDir}/outputs/apk/release/"
    into backupDir
    include '*.apk'
}

task copyDebugApk(type: Copy, dependsOn: 'assembleDebug') {
    from "${buildDir}/outputs/apk/debug/"
    into backupDir
    include '*.apk'
}

assembleRelease.finalizedBy(copyReleaseApk)
assembleDebug.finalizedBy(copyDebugApk)
