# Project-wide Gradle settings.
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# Low-End Device Optimized (Default)
org.gradle.jvmargs=-Xmx768m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true

# Disable file watching (Saves RAM & CPU)
org.gradle.vfs.watch=false

# Disable Native Services (Prevents crashes on Android/Termux)
org.gradle.native=false

# org.gradle.parallel=true
# org.gradle.daemon=false

# AAPT2 (absolute path — do not use $HOME)
android.aapt2FromMavenOverride=/public/acode.plugin.androidbuilder/build-tools/34.0.0/aapt2
